### PR TITLE
Update CNAME

### PR DESCRIPTION
**Pull request by maxsumrall**

### CODE REVIEW

**Comment by Stephan202** [comment]
(Didn't check the docs:) What effect will this PR have?

Reason I ask: currently `http://picnic.tech` redirects to `https://picnicsupermarket.github.io`. That's admittedly suboptimal, but does mean that the site is served over SSL. We don't yet have a certificate for `picnic.tech`, nor have we set up the infra to serve such a certificate.

**Comment by larslockefeer** [comment]
https://letsencrypt.org should be good enough for this. But I believe that it should be possible in a different way as well.

**Comment by larslockefeer** [comment]
This should work: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by maxsumrall** [comment]
I think reaching the site without `www` is something you setup in the DNS. This is for github. I'm not experienced with setting up SSL, but according to Lar's link, there a few more steps with this as one of them. 

For not having `www`, I think I arranged that in my own domain by creating a redirect in the DNS (no idea what the lingo is here) to redirect the url without "www" to the url with "www".

**Comment by quiqueqs** [comment]
I believe I overheard Dimitar being against letsencrypt a few days ago, not sure why though 🤔

**Comment by Stephan202** [comment]
How does this PR relate to the [announced HTTPS support](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)? It'd be nice to use `https://picnic.tech` (but not `http://picnic.tech`...)

**Comment by fhur** [comment]
I was waiting so long for this! I always wanted to host apibot's client side on github pages but couldn't because of this. I'm guessing this is related to https://www.theverge.com/2018/2/8/16991254/chrome-not-secure-marked-http-encryption-ssl

**Pull request closed without merging**
